Update SwanProjects/README.md
Co-authored-by: Enric Tejedor <enric.tejedor.saavedra@cern.ch>

fixed documentation and comments

diff --git a/SwanProjects/bin/swan_bash b/SwanProjects/bin/swan_bash
--- a/SwanProjects/bin/swan_bash
+++ b/SwanProjects/bin/swan_bash
@@ -26,7 +26,7 @@ if [[ $# -gt 0 ]] ; then
              PATH="/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin:$HOME/.local/bin/" \
              bash -c "swan_env $PROJECT $PROJECT_PATH  bash --rcfile  <(echo 'PS1=\"($PROJECT) $PS1 \"') " 
     else
-      echo "Error: project $PROJECT_PATH doesn't exists" >&2
+      echo "Error: project $PROJECT_PATH doesn't exist" >&2
       sleep 60
       exit 1
     fi
